version: 2
jobs:
  test:
    docker:
      - image: circleci/node:9.4
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - yarn-cache-{{ .Branch }}
          - yarn-cache-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn test
      - store_artifacts:
          path: ganache.log

  coverage:
    docker:
      - image: circleci/node:9.4
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - yarn-cache-{{ .Branch }}
          - yarn-cache-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn coverage
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build:
    jobs:
      - test
      - coverage
